### ISSUE TITLE
missing [jsp2thymeleaf-tldgen] dependency

### ISSUE THREAD

**Issue by gyokutoku** [wjase/jsp2tl-maven-plugin#1]
Hi Wraxall,

The [jsp2thymeleaf-tldgen] dependency could not be resolved in this project.
Could you please provide it? many thanks!

pom.xml
 ```
   <dependency> 
      <groupId>com.cybernostics.jsp2thymeleaf</groupId>  
      <artifactId>jsp2thymeleaf-tldgen</artifactId>  
      <version>1.0.0</version> 
    </dependency>  
```

**Comment by wjase** [comment]
Sure I'll have a look tonight. Haven't worked on it for a while... Cheers

**Comment by wjase** [comment]
That took longer than expected - apologies - had to dig up the code from an old machine but put it under one multi-module project  https://github.com/wjase/jsp-thymeleaf-toolkit

**Comment by gyokutoku** [comment]
@wjase I have downloaded it and it works fine. Thanks you so much for your great work!
